source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!

target 'MLVisionExample' do
  pod 'FirebaseMLVision', '0.16.0'
  pod 'FirebaseMLCommon', '0.16.0'
  pod 'FirebaseMLVisionAutoML', '0.16.0'
end
